version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bitgesell-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tjbj3fafrs6w"
s3_prefix = "bitgesell-api"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RegionName=\"eu-central-1\""

